//go:build go1.22

// Package vwrest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vwrest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CompleteGetVideoInfoActivityRequest defines model for CompleteGetVideoInfoActivityRequest.
type CompleteGetVideoInfoActivityRequest struct {
	Error *Error `json:"error,omitempty"`

	// Token Base64-encoded binary token
	Token []byte `json:"token"`
}

// CompleteTranscodeActivityRequest defines model for CompleteTranscodeActivityRequest.
type CompleteTranscodeActivityRequest struct {
	// CompletionPercentage Completion percentage (0-100)
	CompletionPercentage int    `json:"completionPercentage"`
	Error                *Error `json:"error,omitempty"`

	// Token Base64-encoded binary token
	Token []byte `json:"token"`
}

// CreateDiscRequest defines model for CreateDiscRequest.
type CreateDiscRequest struct {
	// Path Path to the directory containing the disc contents
	Path string `json:"path"`

	// Uuid Client-provided UUID for the disc workflow
	Uuid openapi_types.UUID `json:"uuid"`
}

// DiscWorkflow defines model for DiscWorkflow.
type DiscWorkflow struct {
	Path   string             `json:"path"`
	Status string             `json:"status"`
	Uuid   openapi_types.UUID `json:"uuid"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// CompleteGetVideoInfoActivityJSONRequestBody defines body for CompleteGetVideoInfoActivity for application/json ContentType.
type CompleteGetVideoInfoActivityJSONRequestBody = CompleteGetVideoInfoActivityRequest

// CompleteTranscodeActivityJSONRequestBody defines body for CompleteTranscodeActivity for application/json ContentType.
type CompleteTranscodeActivityJSONRequestBody = CompleteTranscodeActivityRequest

// CreateDiscJSONRequestBody defines body for CreateDisc for application/json ContentType.
type CreateDiscJSONRequestBody = CreateDiscRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CompleteGetVideoInfoActivityWithBody request with any body
	CompleteGetVideoInfoActivityWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CompleteGetVideoInfoActivity(ctx context.Context, body CompleteGetVideoInfoActivityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteTranscodeActivityWithBody request with any body
	CompleteTranscodeActivityWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CompleteTranscodeActivity(ctx context.Context, body CompleteTranscodeActivityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDiscWithBody request with any body
	CreateDiscWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDisc(ctx context.Context, body CreateDiscJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CompleteGetVideoInfoActivityWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteGetVideoInfoActivityRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteGetVideoInfoActivity(ctx context.Context, body CompleteGetVideoInfoActivityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteGetVideoInfoActivityRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteTranscodeActivityWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteTranscodeActivityRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteTranscodeActivity(ctx context.Context, body CompleteTranscodeActivityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteTranscodeActivityRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDiscWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDiscRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDisc(ctx context.Context, body CreateDiscJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDiscRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCompleteGetVideoInfoActivityRequest calls the generic CompleteGetVideoInfoActivity builder with application/json body
func NewCompleteGetVideoInfoActivityRequest(server string, body CompleteGetVideoInfoActivityJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCompleteGetVideoInfoActivityRequestWithBody(server, "application/json", bodyReader)
}

// NewCompleteGetVideoInfoActivityRequestWithBody generates requests for CompleteGetVideoInfoActivity with any type of body
func NewCompleteGetVideoInfoActivityRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/activity/get_video_info/complete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCompleteTranscodeActivityRequest calls the generic CompleteTranscodeActivity builder with application/json body
func NewCompleteTranscodeActivityRequest(server string, body CompleteTranscodeActivityJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCompleteTranscodeActivityRequestWithBody(server, "application/json", bodyReader)
}

// NewCompleteTranscodeActivityRequestWithBody generates requests for CompleteTranscodeActivity with any type of body
func NewCompleteTranscodeActivityRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/activity/transcode/complete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateDiscRequest calls the generic CreateDisc builder with application/json body
func NewCreateDiscRequest(server string, body CreateDiscJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDiscRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateDiscRequestWithBody generates requests for CreateDisc with any type of body
func NewCreateDiscRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/disc")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CompleteGetVideoInfoActivityWithBodyWithResponse request with any body
	CompleteGetVideoInfoActivityWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteGetVideoInfoActivityResponse, error)

	CompleteGetVideoInfoActivityWithResponse(ctx context.Context, body CompleteGetVideoInfoActivityJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteGetVideoInfoActivityResponse, error)

	// CompleteTranscodeActivityWithBodyWithResponse request with any body
	CompleteTranscodeActivityWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteTranscodeActivityResponse, error)

	CompleteTranscodeActivityWithResponse(ctx context.Context, body CompleteTranscodeActivityJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteTranscodeActivityResponse, error)

	// CreateDiscWithBodyWithResponse request with any body
	CreateDiscWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDiscResponse, error)

	CreateDiscWithResponse(ctx context.Context, body CreateDiscJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDiscResponse, error)
}

type CompleteGetVideoInfoActivityResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r CompleteGetVideoInfoActivityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteGetVideoInfoActivityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CompleteTranscodeActivityResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r CompleteTranscodeActivityResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteTranscodeActivityResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateDiscResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *DiscWorkflow
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r CreateDiscResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDiscResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CompleteGetVideoInfoActivityWithBodyWithResponse request with arbitrary body returning *CompleteGetVideoInfoActivityResponse
func (c *ClientWithResponses) CompleteGetVideoInfoActivityWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteGetVideoInfoActivityResponse, error) {
	rsp, err := c.CompleteGetVideoInfoActivityWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteGetVideoInfoActivityResponse(rsp)
}

func (c *ClientWithResponses) CompleteGetVideoInfoActivityWithResponse(ctx context.Context, body CompleteGetVideoInfoActivityJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteGetVideoInfoActivityResponse, error) {
	rsp, err := c.CompleteGetVideoInfoActivity(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteGetVideoInfoActivityResponse(rsp)
}

// CompleteTranscodeActivityWithBodyWithResponse request with arbitrary body returning *CompleteTranscodeActivityResponse
func (c *ClientWithResponses) CompleteTranscodeActivityWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteTranscodeActivityResponse, error) {
	rsp, err := c.CompleteTranscodeActivityWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteTranscodeActivityResponse(rsp)
}

func (c *ClientWithResponses) CompleteTranscodeActivityWithResponse(ctx context.Context, body CompleteTranscodeActivityJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteTranscodeActivityResponse, error) {
	rsp, err := c.CompleteTranscodeActivity(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteTranscodeActivityResponse(rsp)
}

// CreateDiscWithBodyWithResponse request with arbitrary body returning *CreateDiscResponse
func (c *ClientWithResponses) CreateDiscWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDiscResponse, error) {
	rsp, err := c.CreateDiscWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDiscResponse(rsp)
}

func (c *ClientWithResponses) CreateDiscWithResponse(ctx context.Context, body CreateDiscJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDiscResponse, error) {
	rsp, err := c.CreateDisc(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDiscResponse(rsp)
}

// ParseCompleteGetVideoInfoActivityResponse parses an HTTP response from a CompleteGetVideoInfoActivityWithResponse call
func ParseCompleteGetVideoInfoActivityResponse(rsp *http.Response) (*CompleteGetVideoInfoActivityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteGetVideoInfoActivityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCompleteTranscodeActivityResponse parses an HTTP response from a CompleteTranscodeActivityWithResponse call
func ParseCompleteTranscodeActivityResponse(rsp *http.Response) (*CompleteTranscodeActivityResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteTranscodeActivityResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateDiscResponse parses an HTTP response from a CreateDiscWithResponse call
func ParseCreateDiscResponse(rsp *http.Response) (*CreateDiscResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDiscResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest DiscWorkflow
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Complete the GetVideoInfo activity
	// (POST /activity/get_video_info/complete)
	CompleteGetVideoInfoActivity(w http.ResponseWriter, r *http.Request)
	// Complete the Transcode activity
	// (POST /activity/transcode/complete)
	CompleteTranscodeActivity(w http.ResponseWriter, r *http.Request)
	// Create a disc workflow
	// (POST /disc)
	CreateDisc(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CompleteGetVideoInfoActivity operation middleware
func (siw *ServerInterfaceWrapper) CompleteGetVideoInfoActivity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteGetVideoInfoActivity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteTranscodeActivity operation middleware
func (siw *ServerInterfaceWrapper) CompleteTranscodeActivity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteTranscodeActivity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDisc operation middleware
func (siw *ServerInterfaceWrapper) CreateDisc(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDisc(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/activity/get_video_info/complete", wrapper.CompleteGetVideoInfoActivity)
	m.HandleFunc("POST "+options.BaseURL+"/activity/transcode/complete", wrapper.CompleteTranscodeActivity)
	m.HandleFunc("POST "+options.BaseURL+"/disc", wrapper.CreateDisc)

	return m
}

type CompleteGetVideoInfoActivityRequestObject struct {
	Body *CompleteGetVideoInfoActivityJSONRequestBody
}

type CompleteGetVideoInfoActivityResponseObject interface {
	VisitCompleteGetVideoInfoActivityResponse(w http.ResponseWriter) error
}

type CompleteGetVideoInfoActivity200Response struct {
}

func (response CompleteGetVideoInfoActivity200Response) VisitCompleteGetVideoInfoActivityResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type CompleteGetVideoInfoActivity400JSONResponse Error

func (response CompleteGetVideoInfoActivity400JSONResponse) VisitCompleteGetVideoInfoActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGetVideoInfoActivity500JSONResponse Error

func (response CompleteGetVideoInfoActivity500JSONResponse) VisitCompleteGetVideoInfoActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CompleteTranscodeActivityRequestObject struct {
	Body *CompleteTranscodeActivityJSONRequestBody
}

type CompleteTranscodeActivityResponseObject interface {
	VisitCompleteTranscodeActivityResponse(w http.ResponseWriter) error
}

type CompleteTranscodeActivity200Response struct {
}

func (response CompleteTranscodeActivity200Response) VisitCompleteTranscodeActivityResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type CompleteTranscodeActivity400JSONResponse Error

func (response CompleteTranscodeActivity400JSONResponse) VisitCompleteTranscodeActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CompleteTranscodeActivity500JSONResponse Error

func (response CompleteTranscodeActivity500JSONResponse) VisitCompleteTranscodeActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDiscRequestObject struct {
	Body *CreateDiscJSONRequestBody
}

type CreateDiscResponseObject interface {
	VisitCreateDiscResponse(w http.ResponseWriter) error
}

type CreateDisc201JSONResponse DiscWorkflow

func (response CreateDisc201JSONResponse) VisitCreateDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDisc400JSONResponse Error

func (response CreateDisc400JSONResponse) VisitCreateDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDisc409JSONResponse Error

func (response CreateDisc409JSONResponse) VisitCreateDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateDisc500JSONResponse Error

func (response CreateDisc500JSONResponse) VisitCreateDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Complete the GetVideoInfo activity
	// (POST /activity/get_video_info/complete)
	CompleteGetVideoInfoActivity(ctx context.Context, request CompleteGetVideoInfoActivityRequestObject) (CompleteGetVideoInfoActivityResponseObject, error)
	// Complete the Transcode activity
	// (POST /activity/transcode/complete)
	CompleteTranscodeActivity(ctx context.Context, request CompleteTranscodeActivityRequestObject) (CompleteTranscodeActivityResponseObject, error)
	// Create a disc workflow
	// (POST /disc)
	CreateDisc(ctx context.Context, request CreateDiscRequestObject) (CreateDiscResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CompleteGetVideoInfoActivity operation middleware
func (sh *strictHandler) CompleteGetVideoInfoActivity(w http.ResponseWriter, r *http.Request) {
	var request CompleteGetVideoInfoActivityRequestObject

	var body CompleteGetVideoInfoActivityJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteGetVideoInfoActivity(ctx, request.(CompleteGetVideoInfoActivityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteGetVideoInfoActivity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteGetVideoInfoActivityResponseObject); ok {
		if err := validResponse.VisitCompleteGetVideoInfoActivityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteTranscodeActivity operation middleware
func (sh *strictHandler) CompleteTranscodeActivity(w http.ResponseWriter, r *http.Request) {
	var request CompleteTranscodeActivityRequestObject

	var body CompleteTranscodeActivityJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteTranscodeActivity(ctx, request.(CompleteTranscodeActivityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteTranscodeActivity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteTranscodeActivityResponseObject); ok {
		if err := validResponse.VisitCompleteTranscodeActivityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDisc operation middleware
func (sh *strictHandler) CreateDisc(w http.ResponseWriter, r *http.Request) {
	var request CreateDiscRequestObject

	var body CreateDiscJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDisc(ctx, request.(CreateDiscRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDisc")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDiscResponseObject); ok {
		if err := validResponse.VisitCreateDiscResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xX7W/bthP+Vwj+fh82QLbo1E5TfVreUBgousB92YaiCGjybLORSJY8OfEK/+8DKckv",
	"kVK3QJNtwL4EinR3fO65547nL1SYwhoNGj3NvlAvFlDw+HhuCpsDwkvA90qCGeuZORWolgpXE/hcgsdg",
	"Zp2x4FBBdALnjAsP/3cwoxn9X7qNn9bB08totE4omhvQwVqCF05ZVEbTjJ5xD8fDHmhhJEgyVZq7FamM",
	"Ewp3PACjGZUv3/8pzwdseoT5VA1u/vh9sqAJnRlXcKQZna4QaEJxZYO1R6f0nK7XCXXwuVQOJM0+1Bg+",
	"bszM9BMIDOgaAt46rn2AcjB7UXkoo6/ACdDI59BO73xjRezGjPzEegPGft5N8PkooQW/U0VZ0GzAWEIL",
	"pav/2Aav0ghziHT+W8lPuonrrIkDjnChvHiwCJbjop3WFccFQUNwAUQqBwKNWxFhNHKllZ7XH7yI72I7",
	"7GabFhrT8NnHv4wN2rkltCyV7Kh3rkBjzzqzVIHSd+/GF2Rm3PbIW+NuZrm53TtyNGJwMmSsB0cvpr3h",
	"QA57/PnguDccHh+PRsMhY4ztEh4PP0R4bRQ56uI3MPtbg+ZBar+XF48cS7/vKWIl5ddofEIuNhi7SLls",
	"+up+t0vYhzl+/fZy8vr01fXlZPLrpCu1Aryvh8LW7VST2LrECFE6B4ehx6O30dqgg4PSM1Ph1MhF7BQo",
	"uMpD2NJa4/CXGkNfmIImVPMiwrkakzeVQYC8L+bw0YNbKgFRwwXXfB76Z0/IoXlQYcwuSIo0miJvKl+a",
	"0CU4X8Uc9FmfhaOMBc2tohl91mf9Z3VxItkpr4dvOge8Do1krkOCaT06IqXWVAOhc96Cjw23e52RJii5",
	"VWE8LIBsurQZTaHiPEQay51YXZcirWoEHs+MXDXMg46QuLW5EjFQ+skbvb1sDw3sb7mH1/sCQVdCfOGt",
	"0b5S6xFjbWqaOKRhURJfCgHez8o8X4WaDCu/H5JKffesW6o645K4JpeEjp7izLFGcJrnUc7gqhaMnebL",
	"ouButVPuh5UTHbbixGZX+G5dbraMg6IkXEsiupaIB+XaWmEeWasPrkz/CfUJhNqWUqXSMKK/Isd4IXvC",
	"iYbb/XFeKZET0bXJBDVuN6r6Nr0nw83W9li6a62F3yS0wQ8DsLc3ddTwYo/Oevf52yVMelEv3oJQMwUy",
	"Vo9IA55ogwTuVCXzIXvx+LjOjZ7lSjSg5moJulKY8oTnDrhcEaVJ6eGf1XqxmITfW+VjtMrN0+zD/W57",
	"ZQTPiYQl5MYWoLE+gia0dGFFWyDaLE3zYLcwHrMTdhKWpNYPG2dkKeJF0BHBZ2nKrervLnrrj+u/AgAA",
	"///SrTb89w8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
